Repository SethHollandsworth/azure-cli-extensions, pull requests merged in 2023-04, with the labels that each got.

#23 Feature/sha256 hash, removing --json flag
  src/confcom/README.md
  src/confcom/azext_confcom/README.md
  src/confcom/azext_confcom/_help.py
  src/confcom/azext_confcom/_params.py
  src/confcom/azext_confcom/custom.py
  src/confcom/azext_confcom/data/internal_config.json
  src/confcom/azext_confcom/security_policy.py
  src/confcom/azext_confcom/template_util.py
  src/confcom/azext_confcom/tests/latest/test_confcom_arm.py
  src/confcom/azext_confcom/tests/latest/test_confcom_image.py
  src/confcom/azext_confcom/tests/latest/test_confcom_scenario.py
  src/confcom/azext_confcom/tests/latest/test_confcom_tar.py
Labels: enhancement

#22 adding warnings for save to file and debug mode.
  src/confcom/azext_confcom/_help.py
  src/confcom/azext_confcom/custom.py
  src/confcom/azext_confcom/template_util.py
Labels: bug, documentation

#20 making it so you can disable allow_elevated via the privileged field …
  src/confcom/azext_confcom/config.py
  src/confcom/azext_confcom/container.py
  src/confcom/azext_confcom/security_policy.py
  src/confcom/azext_confcom/tests/latest/README.md
  src/confcom/azext_confcom/tests/latest/test_confcom_arm.py
  src/confcom/azext_confcom/tests/latest/test_confcom_tar.py
Labels: enhancement

#18 Feature/security context
  src/confcom/.gitignore
  src/confcom/azext_confcom/_params.py
  src/confcom/azext_confcom/config.py
  src/confcom/azext_confcom/container.py
  src/confcom/azext_confcom/custom.py
  src/confcom/azext_confcom/data/customer_rego_policy.txt
  src/confcom/azext_confcom/data/internal_config.json
  src/confcom/azext_confcom/sample_policy.md
  src/confcom/azext_confcom/security_policy.py
  src/confcom/azext_confcom/template_util.py
  src/confcom/azext_confcom/tests/latest/README.md
  src/confcom/azext_confcom/tests/latest/test_confcom_arm.py
  src/confcom/azext_confcom/tests/latest/test_confcom_image.py
  src/confcom/azext_confcom/tests/latest/test_confcom_scenario.py
  src/confcom/requirements.txt
  src/confcom/setup.py
Labels: enhancement

#24 changing default value of no_new_privileges
  src/confcom/azext_confcom/container.py
  src/confcom/azext_confcom/data/internal_config.json
  src/confcom/azext_confcom/tests/latest/test_confcom_arm.py
  src/confcom/azext_confcom/tests/latest/test_confcom_image.py
  src/confcom/azext_confcom/tests/latest/test_confcom_scenario.py
Labels: bug
